title: Blogs
description: Easier & Better
author: AngryRED
github: https://github.com/ecsoya
about: Easier & Better
disqus_shortname: ecsoya
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-weixin
      link: "#"
    - icon: fa-qq
      link: "#"
    - icon: fa-github
      link: "https://github.com/ecsoya"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://ecsoya.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
